name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: x
      run: |
        pwd
        npm install semver --quiet
        echo "::set-env name=PIPER_version::v$(node_modules/.bin/semver -i minor $(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r .tag_name))"
