name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      releaseType:
        required: true
        default: minor
  repository_dispatch:
    types: changeme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: x
      run: |
        echo rel type $INPUT_RELEASETYPE
        npm install semver --quiet
        echo v$(node_modules/.bin/semver -i minor $(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r .tag_name))
        echo "::set-env name=PIPER_version::v$(node_modules/.bin/semver -i minor $(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r .tag_name))"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.PIPER_version }}
        release_name: Release ${{ env.PIPER_version }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
